sonar.projectKey=Notes-App---Abdul-Baseer
sonar.projectName=Notes App - Abdul Baseer
sonar.projectVersion=1.0.0

sonar.sources=backend/src,frontend/src

sonar.tests=backend/tests,frontend/src

sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**,**/dist/**,**/.env,**/tests/**

sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_6a3f010e09a12d940ae38a7acd3314d6237dee32